version: "3.9"

services:
  jupyter:
    build:
      context: .
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - TZ=Asia/Tokyo
      - LANG=en_US.UTF-8
    volumes:
      - ${PWD}:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
